/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Library.java
 *
 * Created on 01-Oct-2010, 11:21:28
 */
package LibraryApplication;

/**
 *
 * @author Esau
 */
import java.sql.*;

public class Library extends javax.swing.JFrame {

    /** Creates new form Library */
    public Library() {
        initComponents();
        mnuMembers.setEnabled(false);
        mnuTransaction.setEnabled(false);
        mnuItems.setEnabled(false);
        mnuAdministration.setEnabled(false);

    }

    public void enable() {
        mnuMembers.setEnabled(true);
        mnuTransaction.setEnabled(true);
        mnuItems.setEnabled(true);
        mnuAdministration.setEnabled(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTransaction = new javax.swing.JMenu();
        mnuNewTransaction = new javax.swing.JMenuItem();
        mnuViewTransactions = new javax.swing.JMenuItem();
        mnuMembers = new javax.swing.JMenu();
        mnuMemberDetails = new javax.swing.JMenuItem();
        mnuAddMember = new javax.swing.JMenuItem();
        mnuItems = new javax.swing.JMenu();
        mnuFindBook = new javax.swing.JMenuItem();
        mnuFindVideo = new javax.swing.JMenuItem();
        mnuFindMagazine = new javax.swing.JMenuItem();
        mnuFindAudio = new javax.swing.JMenuItem();
        mnuBooks = new javax.swing.JMenuItem();
        mnuVideos = new javax.swing.JMenuItem();
        mnumagazine = new javax.swing.JMenuItem();
        mnuAudio = new javax.swing.JMenuItem();
        mnuAdministration = new javax.swing.JMenu();
        mnuUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyLIBRARY");
        setName("MainFrame"); // NOI18N

        desktop.setBackground(new java.awt.Color(51, 51, 51));

        loginLabel.setText("PLEASE LOGIN FIRST ");

        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(73, 23));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setPreferredSize(new java.awt.Dimension(73, 23));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Exit");
        cancelButton.setPreferredSize(new java.awt.Dimension(73, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Username:");

        usernameTextField.setPreferredSize(new java.awt.Dimension(59, 20));

        jLabel2.setText("Password:");

        passwordField.setPreferredSize(new java.awt.Dimension(111, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginPanel.setBounds(280, 150, 400, 190);
        desktop.add(loginPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText("MyLIBRARY");
        usernameLabel.setBounds(390, 10, 450, 14);
        desktop.add(usernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mnuTransaction.setText("Transactions");
        mnuTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTransactionActionPerformed(evt);
            }
        });

        mnuNewTransaction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuNewTransaction.setText("Borrow & Return");
        mnuNewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewTransactionActionPerformed(evt);
            }
        });
        mnuTransaction.add(mnuNewTransaction);

        mnuViewTransactions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        mnuViewTransactions.setText("View Transactions");
        mnuViewTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuViewTransactionsActionPerformed(evt);
            }
        });
        mnuTransaction.add(mnuViewTransactions);

        jMenuBar1.add(mnuTransaction);

        mnuMembers.setText("Members");
        mnuMembers.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuMembersMenuSelected(evt);
            }
        });
        mnuMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMembersActionPerformed(evt);
            }
        });

        mnuMemberDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mnuMemberDetails.setText("Member Details");
        mnuMemberDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMemberDetailsActionPerformed(evt);
            }
        });
        mnuMembers.add(mnuMemberDetails);

        mnuAddMember.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuAddMember.setText("Add Member");
        mnuAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddMemberActionPerformed(evt);
            }
        });
        mnuMembers.add(mnuAddMember);

        jMenuBar1.add(mnuMembers);

        mnuItems.setText("Library");

        mnuFindBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnuFindBook.setText("Find Book");
        mnuFindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindBookActionPerformed(evt);
            }
        });
        mnuItems.add(mnuFindBook);

        mnuFindVideo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnuFindVideo.setText("Find Video");
        mnuFindVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindVideoActionPerformed(evt);
            }
        });
        mnuItems.add(mnuFindVideo);

        mnuFindMagazine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuFindMagazine.setText("Find Magazine");
        mnuFindMagazine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindMagazineActionPerformed(evt);
            }
        });
        mnuItems.add(mnuFindMagazine);

        mnuFindAudio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuFindAudio.setText("Find Audio");
        mnuFindAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFindAudioActionPerformed(evt);
            }
        });
        mnuItems.add(mnuFindAudio);

        mnuBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mnuBooks.setText("Add Book");
        mnuBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBooksActionPerformed(evt);
            }
        });
        mnuItems.add(mnuBooks);

        mnuVideos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        mnuVideos.setText("Add Video");
        mnuVideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVideosActionPerformed(evt);
            }
        });
        mnuItems.add(mnuVideos);

        mnumagazine.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnumagazine.setText("Add Magazine");
        mnumagazine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnumagazineActionPerformed(evt);
            }
        });
        mnuItems.add(mnumagazine);

        mnuAudio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuAudio.setText("Add Audio");
        mnuAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAudioActionPerformed(evt);
            }
        });
        mnuItems.add(mnuAudio);

        jMenuBar1.add(mnuItems);

        mnuAdministration.setText("User Account");

        mnuUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mnuUsers.setText("Users");
        mnuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsersActionPerformed(evt);
            }
        });
        mnuAdministration.add(mnuUsers);

        jMenuBar1.add(mnuAdministration);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMemberDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMemberDetailsActionPerformed
        // TODO add your handling code here:
        MemDetailsFrame memDetails = new MemDetailsFrame();
        desktop.add(memDetails);
        memDetails.setVisible(true);
    }//GEN-LAST:event_mnuMemberDetailsActionPerformed

    private void mnuMembersMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuMembersMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMembersMenuSelected

    private void mnuMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMembersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuMembersActionPerformed

    private void mnuAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddMemberActionPerformed
        // TODO add your handling code here:
        AddMemFrame addMemDetails = new AddMemFrame();
        desktop.add(addMemDetails);
        addMemDetails.setVisible(true);
    }//GEN-LAST:event_mnuAddMemberActionPerformed

    private void mnuTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTransactionActionPerformed
        // TODO add your handling code here:
        viewTransactions transactions = new viewTransactions();
        desktop.add(transactions);
        transactions.setVisible(true);
    }//GEN-LAST:event_mnuTransactionActionPerformed

    private void mnuFindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindBookActionPerformed
        // TODO add your handling code here:
        FindBook book = new FindBook();
        desktop.add(book);
        book.setVisible(true);
    }//GEN-LAST:event_mnuFindBookActionPerformed

    private void mnuFindVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindVideoActionPerformed
        // TODO add your handling code here:
        FindVideo video = new FindVideo();
        desktop.add(video);
        video.setVisible(true);
    }//GEN-LAST:event_mnuFindVideoActionPerformed

    private void mnuFindMagazineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindMagazineActionPerformed
        // TODO add your handling code here:
        FindMagazine magazine = new FindMagazine();
        desktop.add(magazine);
        magazine.setVisible(true);
    }//GEN-LAST:event_mnuFindMagazineActionPerformed

    private void mnuFindAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFindAudioActionPerformed
        // TODO add your handling code here:
        FindAudio audio = new FindAudio();
        desktop.add(audio);
        audio.setVisible(true);
    }//GEN-LAST:event_mnuFindAudioActionPerformed

    private void mnuBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBooksActionPerformed
        // TODO add your handling code here:
        BooksFrame books = new BooksFrame();
        desktop.add(books);
        books.setVisible(true);
    }//GEN-LAST:event_mnuBooksActionPerformed

    private void mnuVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVideosActionPerformed
        // TODO add your handling code here:
        VideosFrame videos = new VideosFrame();
        desktop.add(videos);
        videos.setVisible(true);
    }//GEN-LAST:event_mnuVideosActionPerformed

    private void mnumagazineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnumagazineActionPerformed
        // TODO add your handling code here:
        MagazinesFrame magazine = new MagazinesFrame();
        desktop.add(magazine);
        magazine.setVisible(true);
    }//GEN-LAST:event_mnumagazineActionPerformed

    private void mnuAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAudioActionPerformed
        // TODO add your handling code here:
        AudioFrame audio = new AudioFrame();
        desktop.add(audio);
        audio.setVisible(true);
    }//GEN-LAST:event_mnuAudioActionPerformed

    private void mnuViewTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuViewTransactionsActionPerformed
        // TODO add your handling code here:
        viewTransactions transaction = new viewTransactions();
        desktop.add(transaction);
        transaction.setVisible(true);
    }//GEN-LAST:event_mnuViewTransactionsActionPerformed

    private void mnuNewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewTransactionActionPerformed
        // TODO add your handling code here:
        newTransaction transaction = new newTransaction();
        desktop.add(transaction);
        transaction.setVisible(true);
    }//GEN-LAST:event_mnuNewTransactionActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String feedback = "WRONG LOGIN DETAILS";
        String username = usernameTextField.getText();
        String password = passwordField.getText();
        String name = null;
        //usernameTextField.setText(password + username);
        try {
            ResultSet result = null;
            Connection con = null;
            //Load JBBC driver "com.mysql.jdbc.Driver"
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "");

            PreparedStatement statement = con.prepareStatement("SELECT * FROM library.users WHERE username = '" + username + "'");
            result = statement.executeQuery();

            while (result.next()) {
                if (result.getString(3).equals(password)) {
                    name = result.getString(4);
                    enable();
                    loginPanel.setVisible(false);
                    usernameLabel.setText("Welcome " + name);
                    usernameLabel.setVisible(true);
                } else {
                    feedback = "WRONG PASSWORD";
                }
            }
            loginLabel.setText(feedback);

            result.close();
            con.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_loginButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        usernameTextField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void mnuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsersActionPerformed
        // TODO add your handling code here:
        Users users = new Users();
        desktop.add(users);
        users.setVisible(true);
    }//GEN-LAST:event_mnuUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Library().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JMenuItem mnuAddMember;
    private javax.swing.JMenu mnuAdministration;
    private javax.swing.JMenuItem mnuAudio;
    private javax.swing.JMenuItem mnuBooks;
    private javax.swing.JMenuItem mnuFindAudio;
    private javax.swing.JMenuItem mnuFindBook;
    private javax.swing.JMenuItem mnuFindMagazine;
    private javax.swing.JMenuItem mnuFindVideo;
    private javax.swing.JMenu mnuItems;
    private javax.swing.JMenuItem mnuMemberDetails;
    private javax.swing.JMenu mnuMembers;
    private javax.swing.JMenuItem mnuNewTransaction;
    private javax.swing.JMenu mnuTransaction;
    private javax.swing.JMenuItem mnuUsers;
    private javax.swing.JMenuItem mnuVideos;
    private javax.swing.JMenuItem mnuViewTransactions;
    private javax.swing.JMenuItem mnumagazine;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
